name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        msbuild /m XamarinMultiTenant.sln /verbosity:normal /t:Rebuild /p:Configuration=Debug "/p:Platform=Any CPU"
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore
        msbuild /m XamarinMultiTenant.sln /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
